name: Client CI

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '.github/workflows/client.yml'
      - 'client/.swiftlint.yml'
      - 'client/**/*.swift'
  push:
    branches:
      - main
    paths:
      - '.github/workflows/client.yml'
      - 'client/.swiftlint.yml'
      - 'client/**/*.swift'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Action for SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.2.1
        with:
          args: --strict
