name: Build and Test Next.js with Biome.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Next.js App
      run: npm run build

    - name: Run Biome.js
      run: |
         npm install -g @biomejs/biome
          biome format

    - name: Test Next.js App
      run: npm test
